name: Run tests

on:
  pull_request:
    branches: [ develop ]
    paths:
    - 'backend/src/**'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.14.0
        cache: 'npm'    

    - name: Install dependencies
      working-directory: backend/
      run: npm install

    - name: Run tests
      working-directory: backend/
      run: npm test